## PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: never 
    url: jdbc:postgresql://localhost:5432/cadastros
    username: postgres
    password: postgres
  jpa:
    hibernate:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     ddl-auto: create
    show-sql: false
    

### Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    