## PostgreSQL
spring:  datasource:
    initialization-mode: never 
    url: jdbc:postgresql://localhost:5432/cadastros 
    username: postgres
    password: 124578  jpa:
    hibernate:     ddl-auto: none    show-sql: false

### Swagger

springdoc:  swagger-ui:    path: /swagger-ui.html