## PostgreSQL
spring:  datasource:
    initialization-mode: never 
    url: ${JDBC_DATASOURCE_URL}
    username: postgres
    password: 124578  jpa:
    hibernate:     ddl-auto: create    show-sql: true    

### Swagger

springdoc:  swagger-ui:    path: /swagger-ui.html
    
server:  port: 8080

  