## PostgreSQL
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: never 
    url: jdbc:postgresql://localhost:5432/cadastros-testes
    username: postgres
    password: 124578
  jpa:
    hibernate:
     ddl-auto: create
     database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
